name: CSharpBible CI

on:
  push:
    paths:
      - "CSharpBible/**"
  pull_request:
    paths:
      - "CSharpBible/**"

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: CSharpBible
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore CSharpBible.sln

      - name: Build
        run: dotnet build CSharpBible.sln --configuration Release --no-restore -p:TargetFramework=net8.0

      - name: Test
        run: dotnet test CSharpBible.sln --configuration Release --no-build --verbosity normal -p:TargetFramework=net8.0
